baseURL = "/"
languageCode = "en-us"
title = "A D V A N C E"
disableKinds = ["taxonomy", "taxonomyTerm", "robotsTXT", "sitemap", "RSS"]

[Params]
description = "A training facility for teachers and school leaders"
author = "Ayesha Iqbal <ayeshaiq@gmail.com>"
