[build.environment]
    HUGO_VERSION = "0.72.0"

[[redirects]]
    from = "https://advance-consultancy.netlify.com/*"
    to = "https://advance-consultancy.org/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://advance-consultancy.netlify.app/*"
    to = "https://advance-consultancy.org/:splat"
    status = 301
    force = true