[build.environment]
    HUGO_VERSION = "0.61.0"

[[redirects]]
    from = "https://advance-consultancy.netlify.com/*"
    to = "https://advance-consultancy.org/:splat"
    status = 301
    force = true